# Generated by Django 5.2.11 on 2026-02-28 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('twitter', models.CharField(blank=True, max_length=120)),
                ('tiktok', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('approved_stars', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('approved_rating_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creative_profile', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, related_name='creatives', to='creatives.service')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('design', 'Design'), ('code', 'Code'), ('music', 'Music'), ('writing', 'Writing'), ('other', 'Other')], default='other', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='creatives.creativeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RatingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_stars', models.DecimalField(decimal_places=1, max_digits=2)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_suggestion', to='creatives.creativeprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
