# Generated by Django 5.2.11 on 2026-02-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeprofile',
            name='max_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creativeprofile',
            name='min_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creativeprofile',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
